build:cudampiomp:
  tags: [galileo]
  script:
    - module purge
    - module load profile/global pgi/17.10 cuda/8.0.61
    - ./configure --enable-openmp
    - cd UtilXlib/tests
    - bash compile_and_run_tests.sh -smcn

build:intelmpiomp:
  tags: [galileo]
  script:
    - module purge
    - module load profile/advanced intel/pe-xe-2017--binary intelmpi/2017--binary
    - ./configure --enable-openmp
    - cd UtilXlib/tests
    - bash compile_and_run_tests.sh -sm

build:cudampi:
  tags: [galileo]
  script:
    - module purge
    - module load profile/global pgi/17.10 cuda/8.0.61
    - ./configure
    - cd UtilXlib/tests
    - bash compile_and_run_tests.sh -smcn

build:intelmpi:
  tags: [galileo]
  script:
    - module purge
    - module load profile/advanced intel/pe-xe-2017--binary intelmpi/2017--binary
    - ./configure
    - cd UtilXlib/tests
    - bash compile_and_run_tests.sh -sm
