build:pw:
  tags: [docker]
  image: ubuntu:latest
  script:
    - apt-get update
    - apt-get install --yes build-essential gfortran wget python
    - apt-get install --yes libopenmpi-dev openmpi-bin
    - apt-get install --yes libblas-dev liblapack-dev fftw3 fftw3-dev pkg-config
    - ./configure
    - make pw
#    - export OMP_NUM_THREADS=1
#    - cd test-suite
#    - mkdir /tmp/save
#    - make run-tests-pw-serial
#    - rm -r /tmp/save

build:cp:
  tags: [docker]
  image: ubuntu:latest
  script:
    - apt-get update
    - apt-get install --yes build-essential gfortran wget python
    - apt-get install --yes libopenmpi-dev openmpi-bin
    - apt-get install --yes libblas-dev liblapack-dev fftw3 fftw3-dev pkg-config
    - ./configure
    - make cp
#    - export OMP_NUM_THREADS=1
#    - cd test-suite
#    - mkdir /tmp/save
#    - make run-tests-cp-serial
#    - rm -r /tmp/save

build:ph:
  tags: [docker]
  image: ubuntu:latest
  script:
    - apt-get update
    - apt-get install --yes build-essential gfortran wget python
    - apt-get install --yes libopenmpi-dev openmpi-bin
    - apt-get install --yes libblas-dev liblapack-dev fftw3 fftw3-dev pkg-config
    - ./configure
    - make ph
#    - export OMP_NUM_THREADS=1
#    - cd test-suite
#    - mkdir /tmp/save
#    - make run-tests-ph-serial
#    - rm -r /tmp/save

#build:centos:
#  image: centos:latest
#  script:
#    - yum -y groupinstall "Development Tools" 
#    - yum -y install wget which python27
#    - ./configure
#    - make all
#    - export OMP_NUM_THREADS=1
#    - cd test-suite
#    - mkdir /tmp/save
#    - make run-tests-serial
#    - rm -r /tmp/save


#### BUILDS ON GALILEO ####

build:laxlib-unittest:
  tags: [galileo]
  script:
    - module load profile/advanced pgi/17.10 cuda/8.0.61
    - ./configure && make pw
    - cd LAXlib/tests
    - make clean && make
    - for file in ./*.x; do mpirun -np 4 ./$file; done
    - cd ../../
    - ./configure --disable-parallel && make clean && make pw
    - cd LAXlib/tests
    - make clean && make
    - for file in ./*.x; do ./$file; done
