build:cudaopenmp:
  tags: [galileo]
  script:
    - module load profile/advanced pgi/17.10 cuda/8.0.61
    - ./configure --enable-openmp
    - cd UtilXlib/tests
    - bash gen_and_run_tests.sh -smcn

build:intelopenmp:
  tags: [galileo]
  script:
    - module load profile/advanced intel
    - ./configure --enable-openmp
    - cd UtilXlib/tests
    - bash gen_and_run_tests.sh -sm

build:cuda:
  tags: [galileo]
  script:
    - module load profile/advanced pgi/17.10 cuda/8.0.61
    - ./configure
    - cd UtilXlib/tests
    - bash gen_and_run_tests.sh -smcn

build:intel:
  tags: [galileo]
  script:
    - module load profile/advanced intel
    - ./configure
    - cd UtilXlib/tests
    - bash gen_and_run_tests.sh -sm
